/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Metodos.Listas;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.WindowConstants;
/**
 *
 * @author Anderson
 */
public class Controlador extends javax.swing.JFrame {
    
    String user, nombre_usuario;
    Listas UsuarioTec = new Listas();
    Listas UsuarioMan = new Listas();
    Listas UsuarioCon = new Listas();
    Listas UsuarioAd = new Listas();
    Listas Equipos = new Listas();
    Listas Tiempos = new Listas();

    /**
     * Creates new form Controlador2
     */
    public Controlador(Listas usuario, Listas u, Listas us, Listas usu, Listas equipo, Listas tiempos) {
        initComponents();
        UsuarioCon = usu;
        UsuarioMan = us;
        UsuarioTec = u;
        UsuarioAd = usuario;
        Equipos = equipo;
        Tiempos = tiempos;
        initComponents();
        user = Login.nom;
        
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setSize(550, 300);
        setResizable(false);
        setTitle("Controlador - Sesión de " + user);
        setLocationRelativeTo(null);
        setLocation(300,200);

        ImageIcon wallpaper = new ImageIcon("src/images/Fondo.jpg");
        /*Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);*/
        //this.repaint();

        nombre_usuario = user;
        //jLabel_NombreUsuario.setText("Bienvenido: " + nombre_usuario);*/
    }
    
    public Controlador() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /*
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/User.png"));
        return retValue;
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton_InformacionUsuarios = new javax.swing.JButton();
        jButton_InformacionEquipos = new javax.swing.JButton();
        jButton_InformacionIngreso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel6.setText("Información Usuarios");

        jLabel2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel2.setText("Información Equipos");

        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Informacion de Ingreso");

        jButton_InformacionUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InformacionUsuariosActionPerformed(evt);
            }
        });

        jButton_InformacionEquipos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InformacionEquiposActionPerformed(evt);
            }
        });

        jButton_InformacionIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_InformacionIngresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_InformacionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton_InformacionIngreso, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jButton_InformacionEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_InformacionIngreso, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton_InformacionUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_InformacionEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))))
                .addGap(65, 65, 65))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_InformacionUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InformacionUsuariosActionPerformed
        InformacionUsuario informacionUsuarios = new InformacionUsuario(UsuarioAd, UsuarioTec, UsuarioCon, UsuarioMan);
        informacionUsuarios.setVisible(true);
    }//GEN-LAST:event_jButton_InformacionUsuariosActionPerformed

    private void jButton_InformacionEquiposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InformacionEquiposActionPerformed
        InformacionEquipo informacionEquipos = new InformacionEquipo(Equipos);
        informacionEquipos.setVisible(true);
    }//GEN-LAST:event_jButton_InformacionEquiposActionPerformed

    private void jButton_InformacionIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_InformacionIngresoActionPerformed
        // TODO add your handling code here:
        InformacionIngreso informacionIngreso = new InformacionIngreso(Tiempos);
        informacionIngreso.setVisible(true);
    }//GEN-LAST:event_jButton_InformacionIngresoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Controlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Controlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Controlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Controlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Controlador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_InformacionEquipos;
    private javax.swing.JButton jButton_InformacionIngreso;
    private javax.swing.JButton jButton_InformacionUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
