/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Metodos.Dispositivos;
import Metodos.Listas;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
//import clases.Equipos;
import Metodos.Listas;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Anderson
 */
public class GestionarEquipo extends javax.swing.JFrame {
    
    int IDcliente_update = 0, IDequipo = 0;
    String user = "", nom_cliente = "";
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form InformacionEquipo
     */
    Listas Equipos = new Listas();

    /**
     * Creates new form GestionarEquipo2
     */
    public GestionarEquipo(Listas equipo) {
         initComponents();
        Equipos = equipo;

        user = Login.nom;

        setTitle("Gestionar equipo - Sesión de " + user);
        setSize(680, 450);
        setResizable(false);
        setLocationRelativeTo(null);

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        ImageIcon wallpaper = new ImageIcon("src/images/Fondo.jpg");
        /*Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(),
                jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
        this.repaint();*/

    }
    
    public GestionarEquipo() {
         initComponents();
        this.setLocationRelativeTo(this);
    }
    
       @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/User.png"));
        return retValue;
    }
    
    @SuppressWarnings("unchecked")
    public void llenartabla() {
        jTable_equipos = new JTable(model);
        jScrollPane_equipos.setViewportView(jTable_equipos);
        model.addColumn("Nombre");
        model.addColumn("Dirección IP");
        model.addColumn("Host");
        model.addColumn("Servidor");
        model.addColumn("Puerto");
        model.addColumn("DNS");
        for (int i = 1; i <= 10; i++) {

            try {
                Dispositivos a = Equipos.Indice(i);
                String datos[] = {/*a.getNombre()*/a.getTipo(), a.getIP(), a.getHost(), a.getServidor(), a.getPuerto(), a.getDNS()};
                model.addRow(datos);

            } catch (Exception ex) {
            }

        }
        jTable_equipos.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        txt_IpEquipo = new javax.swing.JTextField();
        jButton_Buscar = new javax.swing.JButton();
        jScrollPane_equipos = new javax.swing.JScrollPane();
        jTable_equipos = new javax.swing.JTable();
        jLabel_Nombre1 = new javax.swing.JLabel();
        cmb_tipoequipo = new javax.swing.JComboBox<>();
        jLabel_Nombre2 = new javax.swing.JLabel();
        cmb_puerto = new javax.swing.JComboBox<>();
        jLabel_Nombre6 = new javax.swing.JLabel();
        txt_dns = new javax.swing.JTextField();
        jButton_ActualizarEquipo = new javax.swing.JButton();
        jLabel_Nombre3 = new javax.swing.JLabel();
        txt_host = new javax.swing.JTextField();
        jLabel_Nombre4 = new javax.swing.JLabel();
        txt_servidor = new javax.swing.JTextField();
        jButton_EliminarEquipo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel_Titulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(0, 0, 51));
        jLabel_Titulo.setText("Gestionar equipo");

        jLabel_Nombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre.setForeground(new java.awt.Color(0, 0, 51));
        jLabel_Nombre.setText("Dirección IP:");

        txt_IpEquipo.setBackground(new java.awt.Color(153, 153, 255));
        txt_IpEquipo.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_IpEquipo.setForeground(new java.awt.Color(255, 255, 255));
        txt_IpEquipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_IpEquipo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_Buscar.setBackground(new java.awt.Color(153, 153, 255));
        jButton_Buscar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_Buscar.setForeground(new java.awt.Color(0, 0, 51));
        jButton_Buscar.setText("Buscar por IP");
        jButton_Buscar.setBorder(null);
        jButton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_BuscarActionPerformed(evt);
            }
        });

        jTable_equipos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane_equipos.setViewportView(jTable_equipos);

        jLabel_Nombre1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel_Nombre1.setText("Tipo de equipo:");

        cmb_tipoequipo.setForeground(new java.awt.Color(0, 0, 51));
        cmb_tipoequipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Router", "Switch", "Access Point" }));

        jLabel_Nombre2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre2.setForeground(new java.awt.Color(0, 0, 51));
        jLabel_Nombre2.setText("Puerto:");

        cmb_puerto.setForeground(new java.awt.Color(0, 0, 51));
        cmb_puerto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "24", "88", "13", "52", "54", " " }));

        jLabel_Nombre6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre6.setForeground(new java.awt.Color(0, 0, 51));
        jLabel_Nombre6.setText("DNS:");

        txt_dns.setBackground(new java.awt.Color(153, 153, 255));
        txt_dns.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_dns.setForeground(new java.awt.Color(255, 255, 255));
        txt_dns.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_dns.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_ActualizarEquipo.setBackground(new java.awt.Color(153, 153, 255));
        jButton_ActualizarEquipo.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_ActualizarEquipo.setForeground(new java.awt.Color(0, 0, 51));
        jButton_ActualizarEquipo.setText("Actualizar equipo");
        jButton_ActualizarEquipo.setBorder(null);
        jButton_ActualizarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ActualizarEquipoActionPerformed(evt);
            }
        });

        jLabel_Nombre3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre3.setForeground(new java.awt.Color(0, 0, 51));
        jLabel_Nombre3.setText("Host:");

        txt_host.setBackground(new java.awt.Color(153, 153, 255));
        txt_host.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_host.setForeground(new java.awt.Color(255, 255, 255));
        txt_host.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_host.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel_Nombre4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel_Nombre4.setForeground(new java.awt.Color(0, 0, 51));
        jLabel_Nombre4.setText("Servidor:");

        txt_servidor.setBackground(new java.awt.Color(153, 153, 255));
        txt_servidor.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        txt_servidor.setForeground(new java.awt.Color(255, 255, 255));
        txt_servidor.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_servidor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton_EliminarEquipo.setBackground(new java.awt.Color(153, 153, 255));
        jButton_EliminarEquipo.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        jButton_EliminarEquipo.setForeground(new java.awt.Color(0, 0, 51));
        jButton_EliminarEquipo.setText("Eliminar equipo");
        jButton_EliminarEquipo.setBorder(null);
        jButton_EliminarEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EliminarEquipoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel_Nombre)
                                .addComponent(txt_IpEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(6, 6, 6)
                                            .addComponent(jLabel_Nombre6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txt_dns, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(cmb_tipoequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel_Nombre1))
                                            .addGap(81, 81, 81)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(cmb_puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel_Nombre2)))))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(49, 49, 49)
                                    .addComponent(jButton_ActualizarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(43, 43, 43)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_EliminarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_Nombre3)
                                .addComponent(txt_host, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel_Nombre4)
                                .addComponent(txt_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(77, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Titulo)
                .addGap(202, 202, 202))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Titulo)
                .addGap(20, 20, 20)
                .addComponent(jLabel_Nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_IpEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_equipos, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel_Nombre1))
                            .addComponent(jLabel_Nombre2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_tipoequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_puerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_dns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Nombre6)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Nombre3)
                        .addGap(5, 5, 5)
                        .addComponent(txt_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel_Nombre4)
                        .addGap(5, 5, 5)
                        .addComponent(txt_servidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_ActualizarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_EliminarEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_BuscarActionPerformed

        int validacion = 0;
        String ipequipo;

        ipequipo = txt_IpEquipo.getText().trim();

        if (ipequipo.equals("")) {
            txt_IpEquipo.setBackground(Color.red);
            validacion++;
        }

        if (validacion == 0) {

            try {
                Equipos.buscarip(ipequipo);
                llenartabla();
            } catch (Exception e) {
                System.err.println("Error al encontrar IP. " + e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
        }
    }//GEN-LAST:event_jButton_BuscarActionPerformed

    private void jButton_ActualizarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ActualizarEquipoActionPerformed
        int validacion = 0;
        String ipequipo, tipo_equipo, puerto, host, servidor, dia_ingreso, mes_ingreso, annio_ingreso, dns;

        ipequipo = txt_IpEquipo.getText().trim();
        tipo_equipo = cmb_tipoequipo.getSelectedItem().toString();
        puerto = cmb_puerto.getSelectedItem().toString();
        host = txt_host.getText().trim();
        servidor = txt_servidor.getText().trim();
        dns = txt_dns.getText().trim();

        if (ipequipo.equals("")) {
            txt_IpEquipo.setBackground(Color.red);
            validacion++;
        }
        if (host.equals("")) {
            txt_host.setBackground(Color.red);
            validacion++;
        }
        if (servidor.equals("")) {
            txt_servidor.setBackground(Color.red);
            validacion++;
        }
        if (servidor.equals("")) {
            txt_dns.setBackground(Color.red);
            validacion++;
        }

        if (validacion == 0) {

            try {
                Equipos.eliminarPorIP(ipequipo);
                Equipos.insertarFinE(new Dispositivos(tipo_equipo, ipequipo, host, servidor, puerto, dns));
                txt_IpEquipo.setBackground(Color.green);
                txt_host.setBackground(Color.green);
                txt_servidor.setBackground(Color.green);
                txt_dns.setBackground(Color.green);
                JOptionPane.showMessageDialog(null, "Actualizar exitoso.");
                this.dispose();

            } catch (Exception e) {
                System.err.println("Error al actualizar equipo. " + e);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.");
        }
    }//GEN-LAST:event_jButton_ActualizarEquipoActionPerformed

    private void jButton_EliminarEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EliminarEquipoActionPerformed
        String ipequipo;
        ipequipo = txt_IpEquipo.getText().trim();
        try {
            Equipos.eliminarPorIP(ipequipo);
            JOptionPane.showMessageDialog(null, "Se elimino el equipo.");
            this.dispose();
        } catch (Exception e) {
            System.err.println("Error al eliminar el equipo. " + e);
        }
    }//GEN-LAST:event_jButton_EliminarEquipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarEquipo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarEquipo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb_puerto;
    private javax.swing.JComboBox<String> cmb_tipoequipo;
    private javax.swing.JButton jButton_ActualizarEquipo;
    private javax.swing.JButton jButton_Buscar;
    private javax.swing.JButton jButton_EliminarEquipo;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Nombre1;
    private javax.swing.JLabel jLabel_Nombre2;
    private javax.swing.JLabel jLabel_Nombre3;
    private javax.swing.JLabel jLabel_Nombre4;
    private javax.swing.JLabel jLabel_Nombre6;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JScrollPane jScrollPane_equipos;
    private javax.swing.JTable jTable_equipos;
    private javax.swing.JTextField txt_IpEquipo;
    private javax.swing.JTextField txt_dns;
    private javax.swing.JTextField txt_host;
    private javax.swing.JTextField txt_servidor;
    // End of variables declaration//GEN-END:variables
}
